// <auto-generated />
using System;
using HttpService.Web.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HttpService.Web.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220129204010_AddedSeedData")]
    partial class AddedSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("HttpService.Web.Server.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2147483646);

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2147483647);

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ab9e6ea-517c-4904-9fa7-46d1d5af277c"),
                            CreatedAt = new DateTime(2022, 1, 29, 21, 40, 10, 817, DateTimeKind.Local).AddTicks(7560),
                            Description = "Best resource for learning C#",
                            Name = "C# Book",
                            Price = 15000L,
                            UpdatedAt = new DateTime(2022, 1, 29, 21, 40, 10, 817, DateTimeKind.Local).AddTicks(7589)
                        },
                        new
                        {
                            Id = new Guid("f2f1f3f4-289d-4299-a082-ade06d8b6abd"),
                            CreatedAt = new DateTime(2022, 1, 29, 21, 40, 10, 817, DateTimeKind.Local).AddTicks(7619),
                            Description = "Best resource for learning ASP.NET Core",
                            Name = "ASP.NET Core Book",
                            Price = 12000L,
                            UpdatedAt = new DateTime(2022, 1, 29, 21, 40, 10, 817, DateTimeKind.Local).AddTicks(7621)
                        },
                        new
                        {
                            Id = new Guid("3987d581-8afa-42ba-a5c9-ee9c43456f01"),
                            CreatedAt = new DateTime(2022, 1, 29, 21, 40, 10, 817, DateTimeKind.Local).AddTicks(7639),
                            Description = "Best resource for learning Entity Framework Core",
                            Name = "Entity Framework Core Book",
                            Price = 14000L,
                            UpdatedAt = new DateTime(2022, 1, 29, 21, 40, 10, 817, DateTimeKind.Local).AddTicks(7640)
                        },
                        new
                        {
                            Id = new Guid("63a439fe-4b71-46ee-8763-e123442a5e1f"),
                            CreatedAt = new DateTime(2022, 1, 29, 21, 40, 10, 817, DateTimeKind.Local).AddTicks(7643),
                            Description = "Best resource for learning Blazor",
                            Name = "Blazor Book",
                            Price = 12000L,
                            UpdatedAt = new DateTime(2022, 1, 29, 21, 40, 10, 817, DateTimeKind.Local).AddTicks(7645)
                        },
                        new
                        {
                            Id = new Guid("0e7af9da-fe60-4574-a2ba-007e8c08eb1c"),
                            CreatedAt = new DateTime(2022, 1, 29, 21, 40, 10, 817, DateTimeKind.Local).AddTicks(7647),
                            Description = "Best resource for learning about RESTful Api's",
                            Name = "RESTful Api Book",
                            Price = 20000L,
                            UpdatedAt = new DateTime(2022, 1, 29, 21, 40, 10, 817, DateTimeKind.Local).AddTicks(7649)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
