// <auto-generated />
using System;
using HttpMessengerApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HttpMessengerApp.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("HttpMessengerApp.Server.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0fa6011c-3e1d-40c2-bf21-d64c794eedc8"),
                            CreatedAt = new DateTime(2022, 1, 29, 23, 17, 11, 824, DateTimeKind.Local).AddTicks(7848),
                            Description = "Best resource for learning C#",
                            Name = "C# Book",
                            Price = 15000L,
                            UpdatedAt = new DateTime(2022, 1, 29, 23, 17, 11, 824, DateTimeKind.Local).AddTicks(7878)
                        },
                        new
                        {
                            Id = new Guid("7066ab64-92f0-4c7c-b9c5-bf633addc7e0"),
                            CreatedAt = new DateTime(2022, 1, 29, 23, 17, 11, 824, DateTimeKind.Local).AddTicks(7955),
                            Description = "Best resource for learning ASP.NET Core",
                            Name = "ASP.NET Core Book",
                            Price = 12000L,
                            UpdatedAt = new DateTime(2022, 1, 29, 23, 17, 11, 824, DateTimeKind.Local).AddTicks(7957)
                        },
                        new
                        {
                            Id = new Guid("5a197706-6775-4156-9fd6-77ad2def8452"),
                            CreatedAt = new DateTime(2022, 1, 29, 23, 17, 11, 824, DateTimeKind.Local).AddTicks(7959),
                            Description = "Best resource for learning Entity Framework Core",
                            Name = "Entity Framework Core Book",
                            Price = 14000L,
                            UpdatedAt = new DateTime(2022, 1, 29, 23, 17, 11, 824, DateTimeKind.Local).AddTicks(7961)
                        },
                        new
                        {
                            Id = new Guid("5bc5b7df-05af-4050-a014-c029cf00ea5c"),
                            CreatedAt = new DateTime(2022, 1, 29, 23, 17, 11, 824, DateTimeKind.Local).AddTicks(7963),
                            Description = "Best resource for learning Blazor",
                            Name = "Blazor Book",
                            Price = 12000L,
                            UpdatedAt = new DateTime(2022, 1, 29, 23, 17, 11, 824, DateTimeKind.Local).AddTicks(7965)
                        },
                        new
                        {
                            Id = new Guid("5692e0af-6770-4cd1-bed3-919c477656b8"),
                            CreatedAt = new DateTime(2022, 1, 29, 23, 17, 11, 824, DateTimeKind.Local).AddTicks(7967),
                            Description = "Best resource for learning about RESTful Api's",
                            Name = "RESTful Api Book",
                            Price = 20000L,
                            UpdatedAt = new DateTime(2022, 1, 29, 23, 17, 11, 824, DateTimeKind.Local).AddTicks(7969)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
